# 🗒️ Syllabus

The lecture slides, notes, tutorials, and assignments will be posted on [this drive](https://drive.google.com/drive/u/0/folders/1fkQICU1yBzqeIOT2grTeTpuRno1mHIDs), feel free to jump on it, but please do not anticipate questions in class, instead [drop me a mail](mailto:niccolo.salvini27@gmail.com) if you are not sure about something. If for any reasons you have trouble accessing the G Drive please contact [your teaching assistant](mailto:niccolo.salvini27@gmail.com)

This schedule is subject to change according to the pace of the class.

This is the first edition of this course, well that's the first time I do it!

to be ready: 


<insert Markdown table>

this is an example built with Google Sheet syllabus hosted on Drive plus [tabletomarkdown.com](https://tabletomarkdown.com/):

| Date        | Description                                                  | Materials                                                                    | Events           |
| ----------- | ------------------------------------------------------------ | ---------------------------------------------------------------------------- | ---------------- |
| Mon Sept 26 | preliminaries, descriptive statistics and test of hypothesis | [slides](https://drive.google.com/open?id=1C8_10ZaVvqOKQ_Syu9xyQeENmiNasqV9) | Lecture          |
| Fri Sept 30 | Intro to RStudio + One-Tailed Hypothesis Testing on a mean   | [slides](https://drive.google.com/open?id=1C8_10ZaVvqOKQ_Syu9xyQeENmiNasqV9) | Lecture + Coding |
| Mon Oct 03  |                                                              |                                                                              | Lecture          |
| Fri Oct 07  |                                                              |                                                                              | Lecture          |
| Mon Oct 10  |                                                              |                                                                              | Lecture          |
| Fri Oct 14  |                                                              |                                                                              | Lecture          |
| Mon Oct 17  |                                                              |                                                                              | Lecture          |
| Fri Oct 21  |                                                              |                                                                              | Lecture          |
| Mon Oct 24  |                                                              |                                                                              | Lecture          |
| Tue Oct 25  |                                                              |                                                                              | Laboratory       |
| Fri Oct 28  |                                                              |                                                                              | Lecture          |
| Mon Nov 07  |                                                              |                                                                              | Lecture          |
| Tue Nov 08  |                                                              |                                                                              | Laboratory       |
| Fri Nov 11  |                                                              |                                                                              | Lecture          |
| Mon Nov 14  |                                                              |                                                                              | Lecture          |
| Tue Nov 15  |                                                              |                                                                              | Laboratory       |
| Fri Nov 18  |                                                              |                                                                              | Lecture          |




